version: "3"
services:
  db:
    image: mysql
    container_name: kdsdb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root12345^&*()
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
      - $PWD/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - $PWD/data:/var/lib/mysql
  kds:
    image: kuchain/kds
    ports:
      - 8083:8083
    links:
      - db
    entrypoint: [ "/code/kds",
                  "-v", "2",
                  "-logtostderr",
                  "--username", "dev",
                  "--password", "dev",
                  "--host", "db",
                  "--nodeUri", "http://121.89.211.107:34568",
                  "--httpPort", "8083" ]
