// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/block/list/{page_size}/{page}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "block"
                ],
                "summary": "区块列表",
                "operationId": "blockList",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页大小",
                        "name": "page_size",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页索引",
                        "name": "page",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.BlockListResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/coin/list/{page_size}/{page}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "coin"
                ],
                "summary": "代币列表",
                "operationId": "coinList",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页大小",
                        "name": "page_size",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页索引",
                        "name": "page",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.CoinListResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/delegate/list/{page_size}/{page}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "delegate"
                ],
                "summary": "投票列表",
                "operationId": "delegateList",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页大小",
                        "name": "page_size",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页索引",
                        "name": "page",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.DelegateListResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/search/{word}/{max}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "聚合搜索",
                "operationId": "search",
                "parameters": [
                    {
                        "type": "string",
                        "description": "搜索关键字",
                        "name": "word",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "响应列表最大长度",
                        "name": "max",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.SearchResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/statistics/homePage": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statistics"
                ],
                "summary": "主页统计",
                "operationId": "homePageStatistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.StatisticsResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/tx/list/{page_size}/{page}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tx"
                ],
                "summary": "交易列表",
                "operationId": "txList",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页大小",
                        "name": "page_size",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页索引",
                        "name": "page",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.TXListResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/validator/list/{type}/{page_size}/{page}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "validator"
                ],
                "summary": "验证人列表",
                "operationId": "validatorList",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "验证人类型",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页大小",
                        "name": "page_size",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页索引",
                        "name": "page",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.ValidatorListResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "web.BlockListResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.BlockResponse"
                    }
                },
                "total": {
                    "description": "总数",
                    "type": "integer"
                }
            }
        },
        "web.BlockResponse": {
            "type": "object",
            "properties": {
                "hash": {
                    "description": "交易HASH",
                    "type": "string"
                },
                "height": {
                    "description": "高度",
                    "type": "integer"
                },
                "time": {
                    "description": "时间",
                    "type": "string"
                },
                "txn": {
                    "description": "交易数量",
                    "type": "integer"
                },
                "validator": {
                    "description": "验证人",
                    "type": "string"
                }
            }
        },
        "web.CoinListResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.CoinResponse"
                    }
                },
                "total": {
                    "description": "总数",
                    "type": "integer"
                }
            }
        },
        "web.CoinResponse": {
            "type": "object",
            "properties": {
                "creator": {
                    "description": "发行人",
                    "type": "string"
                },
                "description": {
                    "description": "描述",
                    "type": "string"
                },
                "issue_amount": {
                    "description": "流通总量",
                    "type": "string"
                },
                "max_supply_amount": {
                    "description": "发型总量",
                    "type": "string"
                },
                "symbol": {
                    "description": "名称",
                    "type": "string"
                },
                "time": {
                    "description": "创建时间",
                    "type": "string"
                }
            }
        },
        "web.DelegateListResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.DelegateResponse"
                    }
                },
                "total": {
                    "description": "总数",
                    "type": "integer"
                }
            }
        },
        "web.DelegateResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "实时投票数",
                    "type": "number"
                },
                "commission_rate": {
                    "description": "佣金比例",
                    "type": "integer"
                },
                "rank": {
                    "description": "排名",
                    "type": "integer"
                },
                "validator": {
                    "description": "节点名",
                    "type": "string"
                }
            }
        },
        "web.SearchResponse": {
            "type": "object",
            "properties": {
                "address_list": {
                    "description": "地址列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "coin_list": {
                    "description": "代币列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "height_list": {
                    "description": "高度列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tx_list": {
                    "description": "交易列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "web.StatisticsResponse": {
            "type": "object",
            "properties": {
                "latest_height": {
                    "description": "最后区块高度",
                    "type": "integer"
                },
                "total_account": {
                    "description": "总账户数",
                    "type": "integer"
                },
                "total_tx": {
                    "description": "总交易数",
                    "type": "integer"
                },
                "total_validator": {
                    "description": "总验证人",
                    "type": "integer"
                }
            }
        },
        "web.TXListResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.TXResponse"
                    }
                },
                "total": {
                    "description": "总数",
                    "type": "integer"
                }
            }
        },
        "web.TXResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "交易总额",
                    "type": "string"
                },
                "denom": {
                    "description": "交易类型",
                    "type": "string"
                },
                "from": {
                    "description": "交易发起方",
                    "type": "string"
                },
                "hash": {
                    "description": "交易HASH",
                    "type": "string"
                },
                "height": {
                    "description": "交易高度",
                    "type": "integer"
                },
                "route": {
                    "description": "交易路由",
                    "type": "string"
                },
                "time": {
                    "description": "交易时间",
                    "type": "string"
                },
                "to": {
                    "description": "交易接收方",
                    "type": "string"
                },
                "type": {
                    "description": "交易类型",
                    "type": "string"
                }
            }
        },
        "web.ValidatorListResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.ValidatorResponse"
                    }
                },
                "total": {
                    "description": "总数",
                    "type": "integer"
                }
            }
        },
        "web.ValidatorResponse": {
            "type": "object",
            "properties": {
                "commission_rate": {
                    "description": "佣金比例",
                    "type": "integer"
                },
                "delegated": {
                    "description": "抵押",
                    "type": "string"
                },
                "rank": {
                    "description": "排名",
                    "type": "integer"
                },
                "validator": {
                    "description": "验证人",
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8080",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "KDS API",
	Description: "This is a sample swagger for KDS",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
